In [2]:
import numpy as np
D = np.array([[1,2],[3,4]])
print(np.copyto(E,D))
E = np.array([[1,2],[3,5]])
print(np.copyto(E,D))
print(E)

None
None
[[1 2]
 [3 4]]


In [5]:
import numpy as np
x= np.array([['a','b'],['c','d']])
y= 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [ ]:
import numpy as np
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]]) 
print(A)

In [8]:
import numpy as np
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
from numpy import matlib 
G = matlib.identity(5)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
H = matlib.randn(3,2)
print(H)

[[ 0.64189871  1.78329382]
 [-1.77350555 -1.16671526]
 [-0.18093944 -0.33490471]]


In [12]:
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np 
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] 
M = np.matrix([[1,2],[3,4]])
for i in range(len(c)): 
    ci = np.matrix([[1,1],[1,0]]) 
    ci[0, 0] = c[i] 
    if (i==0): 
        M = ci 
    else: 
         M = M.dot(ci) 
print(M) 
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [ ]:
import numpy as np
X = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
Y = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
XT = X.T
print(XT)
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
print(A1)
print(A2)
A = A1.dot(A2)
print(A)

[[1 1 1 1 1]
 [1 2 3 4 5]]
[[ 1.1 -0.3]
 [-0.3  0.1]]
[[15]
 [55]]


### BÀI TẬP CHƯƠNG 5


In [21]:
import numpy as np
def bpcuctieu(a): 
    b = []
    o1 = []
    for i in range(len(a)): 
        o1.append(1.0)
        b.append((i+1)*1.0) 
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    from numpy import linalg 
    u_1 =np.linalg.inv(u)
    v = np.dot(u_1, x) 
    A = np.dot(v, y)
    return A 
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print(f"Phương trình tuyến tính: y = {A[0]:.1f} + ({A[1]:.1f})·x")

Phương trình tuyến tính: y = 12.1 + (-1.9)·x
