In [19]:
#1.2.Tích vô hướng, trực giao và ứng dụng 
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a,b)
print (tich)
c =np.dot(a,b)
print(c)

32
32


In [20]:
import numpy as np 
a = np.array([1,2,-3]) 
print(np.linalg.norm(a))
print( np.linalg.norm(a,1))

3.7416573867739413
6.0


In [21]:
import math 
import numpy as np 
a = np.array([1,2,-3]) 
def chuan(a, p):
    return np.linalg.norm(a, p)
print(chuan(a, 1))
print(np.linalg.norm(a,1))
print(chuan(a, 2))
print(np.linalg.norm(a,2))
print(chuan(a, 3))
print(np.linalg.norm(a,3))
print(chuan(a, 1000))
print(np.linalg.norm(a,3))
print(chuan(a, 1000))
print(np.linalg.norm(a,1000))

6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
inf
3.3019272488946263
inf
inf


C:\Users\Kevin Laptop\AppData\Roaming\Python\Python313\site-packages\numpy\linalg\_linalg.py:2788: RuntimeWarning: overflow encountered in power
  absx **= ord


In [22]:
from scipy import linalg 
print(linalg.norm(a)) 
print(linalg.norm(a, 100)) 
print(linalg.norm(a, 1000))

3.7416573867739413
3.0
inf


In [23]:
import numpy as np 
m = 10 
v1 = np.array([5,-4,3]) 
v2 = np.array([4,3,-2]) 
v3 = np.array([-4,-3,-1]) 
v4 = np.array([-9,8,6]) 
mi = np.array([2,5,2,1]) 
M = np.array([v1,v2,v3,v4]) 
MT = M.transpose() 
print(MT)
v = (1.0/m)*MT.dot(mi)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [24]:
#Trang 13

In [25]:
import sympy as sym 
x, y = sym.symbols('x y') 
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]]) 
v = sym.Matrix([0, 1]) 
nghiem = sym.solve([A*xy-v])    
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [26]:
#Trang 14

In [27]:
import sympy 
x, y, Lambda = sympy.symbols('x y Lambda') 
I = sympy.eye(2) 
A = sympy.Matrix([[2,3],[3,-6]]) 
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0) 
nghiem = sympy.solve(phuongtrinh) 
print([sympy.N(phantu,4) for phantu in nghiem]) 
print (sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


In [1]:
import numpy as np
A = np.array([[2, 3],
              [3, -6]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)
lambda_val = 3
I = np.eye(A.shape[0])
M = A - lambda_val * I
print("\nMa trận (A - 3I):")
print(M)
from scipy.linalg import null_space
null_vecs = null_space(M)
print("\nVector riêng tương ứng với lambda = 3:")
print(null_vecs)

[ 3. -7.]
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]

Ma trận (A - 3I):
[[-1.  3.]
 [ 3. -9.]]

Vector riêng tương ứng với lambda = 3:
[[-0.9486833 ]
 [-0.31622777]]


In [28]:
import numpy as np 
A = np.array([[2,3],[3,-6]]) 
D = np.array([[-7,0],[0,3]]) 
P = np.array([[-1.0/3, 3],[1,1]]) 
from numpy import linalg 
from numpy import linalg as LA 
P1 = LA.inv(P)   # tính giá trị nghịch đảo của P 
print (P1) 
print(A.dot(P)) 
print(P.dot(D))
print (D **2)

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[49  0]
 [ 0  9]]


### BÀI TẬP CHƯƠNG 6

In [29]:
# Câu 1:
import numpy as np 
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a)) 
mag = np.sqrt(a @ a ) 
mag = np.sqrt(np.inner(a,a)) 
mag = lambda x : math.sqrt(sum(i** 2 for i in x)) 
mag(a) 

3.7416573867739413

In [30]:
#câu 2:
#a
u = v1
v = v2
print(np.linalg.norm(u - v))



8.660254037844387


In [31]:
#b
import numpy as np
u = v1
v = v2
cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
theta = np.arccos(cos_theta)
print("Góc giữa u và v (radian):", theta)
print("Góc giữa u và v (độ):", np.degrees(theta))

Góc giữa u và v (radian): 1.518249575314988
Góc giữa u và v (độ): 86.98929291307843


In [32]:
#c
import numpy as np
u = v1
v = v2
C = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu trực giao của v lên u:", C)

Phép chiếu trực giao của v lên u: [ 0.27586207  0.20689655 -0.13793103]
