### THI THỰC HÀNH ĐẠI SỐ TUYẾN TÍNH (24/07/2025)
##### Họ tên: Nguyễn Ngọc Thiên
##### MSSV: 2474802010366
#### Đề 01:

##### Câu 1: Phép toán cơ bản trên vector và ma trận 

In [ ]:
import numpy as np

# Khai báo vector và ma trận
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

# a) Tính tổng A + B và tích số 2A + 3B
tong_AB = A + B
tich_2A_3B = 2*A + 3*B

print("a)")
print("Tổng A + B:", tong_AB)
print("Tích số 2A + 3B:", tich_2A_3B)

# b) Tích vô hướng và góc giữa hai vector
tich_vo_huong = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = tich_vo_huong / (norm_A * norm_B)
goc_do = np.degrees(np.arccos(cos_theta))

print("\nb)")
print("Tích vô hướng A · B:", tich_vo_huong)
print("Góc giữa hai vector (độ):", round(goc_do, 3))

# c) Tính tích ma trận C * C^T
CCT = np.dot(C, C.T)
print("\nc)")
print("Ma trận C * C^T:\n", CCT)

a)
Tổng A + B: [2 3 1 6]
Tích số 2A + 3B: [ 3 11  2 14]

b)
Tích vô hướng A · B: -5
Góc giữa hai vector (độ): 99.594

c)
Ma trận C * C^T:
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


##### Câu 2: Nhân ma trận, định thức và hạng ma trận

In [6]:
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích ma trận M × N
tich_MN = np.dot(M, N)
print("a)")
print("Tích ma trận M × N:\n", tich_MN)

# b) Tính định thức của ma trận M
try:
    dinh_thuc_M = np.linalg.det(M)
    print("\nb)")
    print("Định thức của ma trận M:", round(dinh_thuc_M, 3))
except np.linalg.LinAlgError:
    print("\nb)")
    print("Không thể tính định thức vì M không phải là ma trận vuông.")

# c) Tính hạng của ma trận N
hang_N = np.linalg.matrix_rank(N)
print("\nc)")
print("Hạng của ma trận N:", hang_N)

a)
Tích ma trận M × N:
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b)
Định thức của ma trận M: 409.0

c)
Hạng của ma trận N: 4


#####  Câu 3: Nghịch đảo ma trận và giải hệ phương trình

In [ ]:
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])

# a) Tìm ma trận nghịch đảo của P
try:
    P_inv = np.linalg.inv(P)
    print("a)")
    print("Ma trận nghịch đảo của P:\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a)")
    print("Ma trận P không khả nghịch vì định thức bằng 0.")

# b) Giải hệ phương trình bằng nghịch đảo ma trận
if 'P_inv' in locals():
    x = np.dot(P_inv, b)
    print("\nb)")
    print("Nghiệm của hệ phương trình là:\n", np.round(x, 3))
else:
    print("\nb)")
    print("Không thể giải hệ bằng nghịch đảo vì P không khả nghịch.")

# c) Kiểm tra nghiệm
if 'x' in locals():
    b_check = np.dot(P, x)
    print("\nc)")
    print("Kiểm tra nghiệm, P.x =\n", np.round(b_check, 3))
    print("Vector hằng số b =\n", b)
else:
    print("\nc)")
    print("Không có nghiệm để kiểm tra.")
if np.allclose(b_check, b):
    print("Nghiệm đúng.")
else:
    print("Nghiệm không đúng.")

a)
Ma trận nghịch đảo của P:
 [[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b)
Nghiệm của hệ phương trình là:
 [2.    1.714 0.429 0.857]

c)
Kiểm tra nghiệm, P.x =
 [6. 8. 3. 7.]
Vector hằng số b =
 [6 8 3 7]
Nghiệm đúng.


##### Câu 4: Giá trị riêng, vector riêng và chuẩn hóa

In [4]:
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# a) Tìm các giá trị riêng của Q
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a)")
print("Các giá trị riêng của Q:", np.round(eigenvalues, 3))

# b) Tìm các vector riêng tương ứng
print("\nb)")
print("Các vector riêng của Q (cột):\n", np.round(eigenvectors, 3))

# c) Chuẩn hóa các vector riêng (độ dài bằng 1)
print("\nc)")
normalized_vectors = []
for v in eigenvectors.T:
    norm_v = v / np.linalg.norm(v)
    normalized_vectors.append(norm_v)
normalized_vectors = np.array(normalized_vectors)
print("Các vector riêng đã chuẩn hóa (mỗi hàng là một vector):\n", np.round(normalized_vectors, 3))

a)
Các giá trị riêng của Q: [6.355+0.j    2.822+1.077j 2.822-1.077j]

b)
Các vector riêng của Q (cột):
 [[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c)
Các vector riêng đã chuẩn hóa (mỗi hàng là một vector):
 [[ 0.748+0.j    -0.189+0.j     0.636+0.j   ]
 [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
 [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]]


##### Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích

In [5]:
import numpy as np
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b bằng np.linalg.solve()
x1 = np.linalg.solve(R, b)
print("a)")
print("Nghiệm của hệ Rx = b bằng np.linalg.solve():\n", np.round(x1, 3))

# b) Kiểm tra khả nghịch, tính nghịch đảo và giải lại hệ
det_R = np.linalg.det(R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
    print("\nb)")
    print("Ma trận R khả nghịch. Ma trận nghịch đảo của R:\n", np.round(R_inv, 3))
    print("Nghiệm của hệ bằng nghịch đảo:\n", np.round(x2, 3))
    print("So sánh hai nghiệm:", np.allclose(x1, x2))
else:
    print("\nb)")
    print("Ma trận R không khả nghịch (định thức bằng 0).")

# c) Tính chuẩn Frobenius của ma trận R
fro_norm = np.linalg.norm(R, 'fro')
print("\nc)")
print("Chuẩn Frobenius của ma trận R:", round(fro_norm, 3))

a)
Nghiệm của hệ Rx = b bằng np.linalg.solve():
 [2.788 1.529 1.188]

b)
Ma trận R khả nghịch. Ma trận nghịch đảo của R:
 [[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm của hệ bằng nghịch đảo:
 [2.788 1.529 1.188]
So sánh hai nghiệm: True

c)
Chuẩn Frobenius của ma trận R: 8.0
