CHƯƠNG 2: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN
TÍNH
1. Dẫn nhập – Một số hàm về xử lý vector với Python 

Hàm “scale” tỉ số vector bằng một giá trị thực: $\vec{v} =(a,b) \Rightarrow k\vec{v} = (ka,kb)$


In [2]:
def scale(a, v):
    return [a * vi for vi in v]
v = [3, 5, 7]
print("Vector sau khi scale:", scaled_v)

Vector sau khi scale: [30, 50, 70]


Hàm lấy tổng hai vector: $\vec{v} = (a, b),\ \vec{w} = (c, d) \Rightarrow \vec{v} + \vec{w} = (a + c,\ b + d)$

In [3]:
def sumvector(v, w):
    return [vi + wi for vi, wi in zip(v, w)]
v = [3, 5, 7]
w = [2, 4, 6]
sum_v_w = sumvector(v, w)
print("Tổng hai vector:", sum_v_w)

Tổng hai vector: [5, 9, 13]


Hàm nhân 2 vector vô hướng: $\vec{u} = (a, b),\ \vec{v} = (c, d) \Rightarrow \vec{u} \cdot \vec{v} = a \times c + b \times d$


In [4]:
def dotvector(v, w):
    return sum(vi * wi for vi, wi in zip(v, w))
v = [3, 5, 7]
w = [2, 4, 6]
dot_v_w = dotvector(v, w)
print("Tích vô hướng:", dot_v_w)

Tích vô hướng: 68


Hàm tính chiều dài một vector: $\vec{u} = (a, b) \Rightarrow \vec{u} \cdot \vec{u} = a^2 + b^2 \Rightarrow |\vec{u}| = \sqrt{a^2 + b^2}$


In [5]:
def lengthvector(v):
    return dotvector(v, v) ** 0.5
v = [3, 5, 7]
length_v = lengthvector(v)
print("Độ dài vector v:", length_v)

Độ dài vector v: 9.1104335791443


2. Bài toán ứng dụng 1 – Phân loại tuyến tính

- Chúng ta thử nghiệm các đoạn lệnh dưới đây để thấy khả năng xử lý của Python với một phân
loại tuyến tính: 

In [2]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4]) 
scores >= 0

array([False,  True,  True, False,  True, False])

In [3]:
scores >= 0 

array([False,  True,  True, False,  True, False])

In [4]:
scores < 0 

array([ True, False, False,  True, False,  True])

In [10]:
np.select([scores >= 0, scores < 0], ['số dương', 'số âm'], default='không xác định')

array(['số âm', 'số dương', 'số dương', 'số dương', 'số âm', 'số dương',
       'số dương', 'số âm'], dtype='<U14')

In [9]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores > 0, scores == 0, scores < 0], ['số dương', 'số 0', 'số âm'], default='không xác định')

array(['số âm', 'số dương', 'số dương', 'số 0', 'số âm', 'số dương',
       'số 0', 'số âm'], dtype='<U14')

BÀI TẬP CHƯƠNG 2 

Câu 1: Hãy sử dụng numpy để giải các phương trình sau: 

Vấn đề 1 (Problem 1): Tìm điểm giao giữa hai đường thẳng trong R^2

In [13]:
import numpy as np
A = np.array([[0, 1], [2, 3]])
b = np.array([-2, 6])
solution_bai1 = np.linalg.solve(A, b)
print("Điểm giao trong R^2:", solution_bai1)

Điểm giao trong R^2: [ 6. -2.]


Vấn đề 2 (Problem 2): Tìm giao điểm giữa ba mặt phẳng trong ℝ^3

In [14]:
A = np.array([[1, -1, 0], [2, -1, 0], [1, 1, 1]])
b = np.array([-2, -3, 6])
solution_bai2 = np.linalg.solve(A, b)
print("Điểm giao trong R^3:", solution_bai2)

Điểm giao trong R^3: [-1.  1.  6.]


Vấn đề 3 (Problem 3): Tìm các hệ số đa thức để đa thức thỏa các nghiệm.

In [15]:
A = np.array([[1**2, 1, 1], [2**2, 2, 1], [3**2, 3, 1]])
b = np.array([4, 3, 4])
coefficients = np.linalg.solve(A, b)
a, b_coeff, c = coefficients
print("Hệ số đa thức bậc 2: a =", a, ", b =", b_coeff, ", c =", c)

Hệ số đa thức bậc 2: a = 1.0000000000000004 , b = -4.000000000000001 , c = 7.000000000000001


Vấn đề 4 (Problem 4)Tìm các hệ đa thức khi phân rã để tính tích phân.

In [ ]:
from scipy.integrate import quad

def integrand(x):
    return x * (x - 3) / (x**2 + 2)

result, error = quad(integrand, 1, 2)
print("Kết quả tích phân:", result)

Câu 2: Hãy viết các câu lệnh của sympy để giải các phương trình ở Câu 1. 

In [ ]:
import numpy as np
from scipy.special import comb
from scipy.integrate import quad
import sympy as sp

x, y = sp.symbols('x y')
equ1 = sp.Eq(x, y)
equ2 = sp.Eq(2*x + 3*y, 6)
solution = sp.solve([equ1, equ2], (x, y))
print("Nghiệm hệ phương trình trong R^2:", solution)

Câu 3: Tính lũy thừa bậc k của ma trận _` = \ \
\ a
`
và chứng minh ma trận _` chứa 3 phần
tử của I9bc-, I9b và I9bJ- của dãy Fibonacci (bắt đầu bằng 0 từ phần tử 0)

In [20]:
import numpy as np

def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[-1] + fib[-2])
    return fib
k = 3  
F_k = np.array([[1, 1], [1, 0]])  
F_k_power = np.linalg.matrix_power(F_k, k)
print(f"Ma trận F_{k}^{{{k}}}:\n{F_k_power}")
fib_sequence = fibonacci(k+1)  
print("Các phần tử của dãy Fibonacci bắt đầu từ 0 đến index", k+1, ":", fib_sequence)
sum_fib = sum(fib_sequence)
print("Tổng các phần tử của dãy Fibonacci đến index", k+1, ":", sum_fib)

Ma trận F_3^{3}:
[[3 2]
 [2 1]]
Các phần tử của dãy Fibonacci bắt đầu từ 0 đến index 4 : [0, 1, 1, 2]
Tổng các phần tử của dãy Fibonacci đến index 4 : 4
